name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
#   nightly build
    - cron: "25 20 * * *"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://pinginx.dannyrollo.com/nexus3/
        username: nexus-repo-github-action-test-user
        password: ${{ secrets.nxrm_password }}
        format: raw
        repository: raw-github-action-test
        coordinates: name=com.example version=1.0.0
        assets: extension=bin
        filename: ./gh-action-test
